[package]
name = "sysy_compiler"
version = "0.1.0"
edition = "2021"
authors = ["Yifan Huang <1900012913@pku.edu.cn>", ]

[build-dependencies]
lalrpop = "0.20.0"

[dependencies]
lalrpop-util = { version = "0.20.0", features = ["lexer"] }
